// AccessibilityInterfaces.cppm
export module AccessibilityInterfaces;

import <memory>;
import <string_view>;
import <vector>;
import <cstdint>;
import <optional>;

// Placeholder for the remote binder connection interface.
// In a real scenario, this would be generated by an AIDL compiler.
export class IRemoteAccessibilityInputConnection {
public:
    virtual ~IRemoteAccessibilityInputConnection() = default;
    // Methods like getText(), commitText(), etc., would be defined here.
};

// Represents information about the text editor.
// This is a simplified C++ version of Android's EditorInfo.
export struct EditorInfo {
    std::optional<std::string> initial_text;
    std::int32_t input_type{};
    // ... other fields would go here
};

// Strong type for session IDs to prevent misuse.
export struct SessionId {
    std::int32_t value;
    auto operator<=>(const SessionId&) const = default;
};

// The core abstract interface for the session.
export class IAccessibilityInputMethodSession {
public:
    virtual ~IAccessibilityInputMethodSession() = default;

    [[nodiscard]] virtual auto set_enabled(bool enabled) -> void = 0;
    
    [[nodiscard]] virtual auto finish_input() -> void = 0;

    [[nodiscard]] virtual auto update_selection(
        std::int32_t old_sel_start, std::int32_t old_sel_end,
        std::int32_t new_sel_start, std::int32_t new_sel_end,
        std::int32_t candidates_start, std::int32_t candidates_end) -> void = 0;

    [[nodiscard]] virtual auto invalidate_input(
        EditorInfo editor_info,
        std::shared_ptr<IRemoteAccessibilityInputConnection> connection,
        SessionId session_id) -> void = 0;
};