// AccessibilityInterfaces.cppm
export module AccessibilityInterfaces;

import <memory>;
import <string_view>;
import <vector>;
import <cstdint>;
import <optional>;

export namespace android::accessibilityservice {
// Placeholder for the remote binder connection interface.
// In a real scenario, this would be generated by an AIDL compiler.
export class IRemoteAccessibilityInputConnection {
public:
    virtual ~IRemoteAccessibilityInputConnection() = default;
    // Methods like getText(), commitText(), etc., would be defined here.
};

// Represents information about the text editor.
// This is a simplified C++ version of Android's EditorInfo.
export struct EditorInfo {
    std::optional<std::string> initial_text;
    std::int32_t input_type{};
    // ... other fields would go here
};

// Strong type for session IDs to prevent misuse.
export struct SessionId {
    std::int32_t value;
    auto operator<=>(const SessionId&) const = default;
};

/**
 * @brief Abstract interface for an accessibility input method session.
 *
 * This mirrors the AIDL contract, providing a pure C++ interface for
 * developers to implement their input method logic.
 */
class IAccessibilityInputMethodSession {
public:
    virtual ~IAccessibilityInputMethodSession() = default;

    virtual void set_enabled(bool enabled) = 0;
    virtual void update_selection(int32_t old_sel_start, int32_t old_sel_end,
                                  int32_t new_sel_start, int32_t new_sel_end,
                                  int32_t candidates_start, int32_t candidates_end) = 0;
    virtual void finish_input() = 0;

    virtual void invalidate_input(
        EditorInfo editor_info,
        std::shared_ptr<IRemoteAccessibilityInputConnection> connection,
        SessionId session_id) = 0;
};
}