#pragma once
#include <cstdint>
#include <errno.h>

typedef int32_t binder_status_t;
enum {
    STATUS_OK = 0,
    STATUS_UNKNOWN_ERROR = (-2147483647 - 1),
    STATUS_NO_MEMORY = -ENOMEM,
    STATUS_INVALID_OPERATION = -ENOSYS,
    STATUS_BAD_VALUE = -EINVAL,
    STATUS_BAD_TYPE = -10,
    STATUS_NAME_NOT_FOUND = -ENOENT,
    STATUS_PERMISSION_DENIED = -EPERM,
    STATUS_NO_INIT = -ENODEV,
    STATUS_ALREADY_EXISTS = -EEXIST,
    STATUS_DEAD_OBJECT = -32,
    STATUS_FAILED_TRANSACTION = -129,
    STATUS_BAD_INDEX = -75,
    STATUS_NOT_ENOUGH_DATA = -61,
    STATUS_WOULD_BLOCK = -EAGAIN,
    STATUS_TIMED_OUT = -ETIMEDOUT,
    STATUS_UNKNOWN_TRANSACTION = -EBADMSG,
    STATUS_FDS_NOT_ALLOWED = -7,
    STATUS_UNEXPECTED_NULL = -111,
};
